-- sublet-skills schema — reference doc, regenerated 2026-09-21 by direct
-- introspection of the live Supabase project (ref cteunhuxrghpozwbnehh).
--
-- This file replaces the pre-2026-09-15 bootstrap, which described a flat
-- `sublet_`-prefixed schema (sublet_listings, sublet_groups, sublet_events,
-- ...) that no longer exists. The live schema was normalized across 15+
-- migrations (see `supabase migrations list` / mcp__supabase__list_migrations)
-- with no `sublet_` prefix anywhere and a separate `posters` identity table.
-- This file is DOCUMENTATION, not a bootstrap script — do not run it against
-- a fresh project expecting it to recreate the real schema exactly; treat it
-- as the source of truth for table/column names when writing or reviewing
-- SQL, and re-derive it from the live DB if it drifts again.
--
-- RLS is enabled on every table below. Most have one explicit
-- `deny_data_api` policy blocking anon/authenticated; two (`poster_duplicate_
-- posts`, `outreach_availability_answers`) currently have RLS enabled with no
-- explicit policy, which still fail-closes to service_role only but is
-- inconsistent with the others (flagged, not yet fixed as of 2026-09-21).
-- Only `service_role` (server-side: Supabase MCP, or `scripts/db.py` via RPC
-- `sublet_exec`) reads/writes.

-- ---------- extensions ----------
-- pgcrypto: gen_random_uuid() for all PKs.
-- pg_trgm: text similarity (used to audit/dedupe poster_duplicate_posts).
--   Installed in schema `public` — Supabase advisor flags this as a WARN
--   (should live in a dedicated schema); not yet moved.

-- ---------- helper functions ----------
-- touch_updated_at() -- trigger function, sets NEW.updated_at = now()
--   (equivalent of the old sublet_touch(); same idea, renamed).
-- fb_identity(profile_url text, name text) returns text
--   -- poster dedup key, used as posters.fb_uid's generated-column expression:
--   /user/[0-9]+ in profile_url -> that numeric id
--   profile.php?id=[0-9]+ in profile_url -> that numeric id
--   facebook.com/[0-9]+ in profile_url -> that numeric id
--   otherwise, profile_url present -> lowercased facebook.com/<slug>
--   otherwise, name present -> 'name:' || lower(name)
--   otherwise -> null (an anonymous poster with no name/profile_url cannot
--   get a posters row at all -- this is intentional, see
--   sublet-scrape-14-groups/SKILL.md).
-- url_encode(text) returns text -- used by dashboardkien_outreach to build a
--   Facebook search-URL fallback for poster_profile_url when nothing better
--   is on file.
-- sublet_exec(q text) returns jsonb -- generic SQL executor, service_role
--   only (revoked from anon/authenticated). This RPC was deleted once
--   (2026-09-17) for being a broad arbitrary-SQL-execution surface, then
--   recreated 2026-09-21 at Kien's explicit request because scripts/db.py
--   and the Codex path depend on it and have no replacement yet. Keep this
--   history in mind before deleting or recreating it again.

-- ---------- groups ----------
create table if not exists groups (
  id text primary key,                    -- was sublet_groups.key; slug, e.g. 'amsterdam-rooms-303940726659024'
  name text not null,
  url text unique,
  city text,
  tier int check (tier in (1,2,3)),
  is_private boolean,
  member_count int,
  allows_sublet text default 'unknown' check (allows_sublet in ('yes','no','unknown')),
  allows_agencies text default 'unknown' check (allows_agencies in ('yes','no','unknown')),
  joined boolean not null default false,
  notif_all_posts boolean not null default false,
  offering_7d int default 0,
  last_post_seen_at timestamptz,
  last_scanned_at timestamptz,
  last_ranked_at timestamptz,
  discovered_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  notes text
);
-- 103 rows as of 2026-09-21.

create table if not exists group_metrics (
  id bigint generated by default as identity primary key,
  group_id text references groups(id),
  checked_at timestamptz not null default now(),
  join_status text check (join_status in ('joined','pending','not_joined','blocked','unknown')),
  member_count int,
  posts_per_day numeric,
  last_active_post_at timestamptz,
  last_active_label text,
  last_active_post_url text,
  membership_questions jsonb,
  activity_sample jsonb,
  source text default 'facebook_panel',
  -- legacy column names; the live capture window is `window_days` calendar
  -- days (currently 7 -- see sublet-scrape-14-groups/SKILL.md), not 14.
  posts_14d_count int,
  posts_14d_complete boolean not null default false,
  posts_14d_checked_at timestamptz
);
-- 158 rows.

-- ---------- posters (identity, did NOT exist pre-2026-09-17) ----------
create table if not exists posters (
  id uuid primary key default gen_random_uuid(),
  name text,
  profile_url text,
  type text not null default 'individual' check (type in ('individual','company','anonymous')),
  is_verified boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  fb_uid text generated always as (fb_identity(profile_url, name)) stored unique,
  outreach_unavailable boolean not null default false,
  outreach_unavailable_reason text
);
-- 797 rows. One row per real person, deduped by fb_uid (see fb_identity above)
-- -- this replaces text `poster_name` columns scattered across the old
-- sublet_listings-era tables.

-- ---------- posts (was sublet_listings, now capture-only + intent) ----------
create table if not exists posts (
  id uuid primary key default gen_random_uuid(),
  source text not null check (source in ('fb_feed','fb_notif','fb_email','form','manual')),
  url text unique,                        -- was source_url
  group_id text references groups(id),    -- was group_key
  poster_id uuid references posters(id),  -- did not exist pre-2026-09-17
  posted_at timestamptz,
  seen_at timestamptz not null default now(),
  body text,                              -- was raw_text
  body_hash text generated always as (md5(lower(regexp_replace(body, '\s+', ' ', 'g')))) stored,
  intent text check (intent in ('offering','seeking','other')),   -- was kind
  subtype text check (subtype in ('sublet_whole','sublet_room','takeover','roommate','swap','short_stay','long_term','seek_sublet','seek_room','seek_group')),
  confidence text check (confidence in ('high','medium','low')),
  scam_score int not null default 0,
  scam_flags text[] not null default '{}',
  canonical_post_id uuid references posts(id),   -- was canonical_id
  status text not null default 'new' check (status in ('new','contacted','replied','declined','closed','dead')),
  link_status text not null default 'unvalidated' check (link_status in ('unvalidated','validated','inaccessible','needs_review')),  -- was link_validation_status
  link_url text,
  link_checked_at timestamptz,
  link_attempts int not null default 0,
  link_note text,
  language text,
  analyzed_at timestamptz,
  updated_at timestamptz not null default now(),
  outreach_order bigint  -- legacy stored value; dashboardkien_outreach computes the live authoritative order, do not read this column
);
-- 1,123 rows. poster_name/area/rent/etc. from the old flat sublet_listings
-- moved to posters and post_details respectively.

-- 1:1 with posts -- area/rent/dates/requirements etc.
create table if not exists post_details (
  post_id uuid primary key references posts(id),
  areas text[] not null default '{}',           -- was single `area` text
  room_type text check (room_type in ('room','studio','apartment','other')),
  price_eur int,                                -- rent when offering, budget when seeking; was rent_eur
  deposit_eur int,
  bills_included text,
  available_from date,
  available_to date,
  min_term_days int,
  flex_days int,
  max_people int,
  furnished boolean,
  registration_allowed text not null default 'unknown' check (registration_allowed in ('yes','no','unknown')),
  sublet_permission text not null default 'unknown' check (sublet_permission in ('yes','no','unknown')),
  availability text not null default 'unknown' check (availability in ('unknown','available','taken')),
  requirements text,                            -- was poster_constraints
  notes text,
  updated_at timestamptz not null default now()
);
-- 1,122 rows (1 post currently missing its post_details row -- mid-pipeline, not a bug by itself).

-- did not exist before; currently unused (0 rows) -- reserved for future
-- likes/shares/comments tracking, nothing writes to it yet.
create table if not exists post_metrics (
  post_id uuid primary key references posts(id),
  total_likes int,
  total_comments int,
  total_shares int,
  total_replies int,
  edited_at timestamptz,
  captured_at timestamptz not null default now()
);

create table if not exists post_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references posts(id),
  commenter_id uuid references posters(id),
  url text,
  body text,
  signal text,
  is_poster boolean not null default false,
  commented_at timestamptz,
  created_at timestamptz not null default now()
);
-- 61 rows.

-- reconciliation table for poster_duplicate_posts: a post_id here is
-- excluded from dashboardkien_outreach's candidate pool because it is a
-- repost/duplicate of primary_post_id by the same poster. Populated by a
-- one-off dedup pass (see docs/dashboard-source-of-truth.md, "Known open
-- gap"), not by a living skill as of 2026-09-21 -- new duplicates from future
-- capture are not automatically added here yet.
create table if not exists poster_duplicate_posts (
  post_id uuid primary key references posts(id),
  poster_id uuid not null references posters(id),
  poster_name text,
  post_link text,
  primary_post_id uuid not null references posts(id),
  seen_at timestamptz,
  moved_at timestamptz not null default now()
);
-- 284 rows (as of 2026-09-21, after removing 79 false-positive rows whose
-- pg_trgm body similarity to their "primary" was < 0.5 -- see conversation
-- history / commit log, not reproduced here).

-- ---------- outreach ----------
create table if not exists outreach_messages (
  id uuid primary key default gen_random_uuid(),
  direction text not null check (direction in ('out','in')),
  channel text not null check (channel in ('fb_dm','whatsapp','email','telegram','other')),
  template text,   -- 'message1' (current) or legacy 'availability_check_*' names; 'message2' for the follow-up stage
  body text,
  status text not null default 'draft' check (status in ('draft','approved','sent','received')),
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  in_reply_to uuid references outreach_messages(id),
  post_id uuid references posts(id),
  poster_id uuid references posters(id)
);
-- 277 rows. Was sublet_messages. Partial unique indexes enforce "one sent
-- message1 per poster" and "one sent template per poster" at the DB layer --
-- see indexes below.

-- one row per poster who has been asked the availability-check question.
-- IMPORTANT: `availability_answer` defaults to 'no' at the column level, but
-- a default row is NOT the same as a real "no" reply -- as of 2026-09-21,
-- 413/666 rows (62%) have this default with zero outreach_messages ever sent
-- to that poster. dashboardkien_outreach.availability_answer corrects for
-- this (shows 'not_asked' when answer1 is null); querying this base table
-- directly still needs the same check (`answer1 is not null`) to avoid
-- treating "never asked" as "declined".
create table if not exists outreach_availability_answers (
  poster_id uuid primary key references posters(id),
  availability_answer text not null default 'no' check (availability_answer in ('yes','no','unclear')),
  updated_at timestamptz not null default now(),
  answer1 text,
  message2 text,
  answer2 text,
  answer2_at timestamptz,
  use_of_service_agreement text check (use_of_service_agreement is null or use_of_service_agreement in ('yes','no'))
);
-- 666 rows.

-- ---------- events (provenance, append-only) ----------
create table if not exists events (
  id bigint generated always as identity primary key,
  entity_type text not null,   -- 'post' (not 'listing' anymore), 'fb_card', 'group', etc.
  entity_id uuid,
  event text not null,
  actor text not null default 'agent' check (actor in ('agent','human','system')),
  source_url text,
  payload jsonb,
  created_at timestamptz not null default now()
);
-- 4,402+ rows. Carries the same hard DB-level constraint as before:
--   capture_unresolved_reason_check: event <> 'capture_unresolved' or
--   payload->>'unresolved_reason' = 'no_link_evidence' (NOT VALID, enforced
--   on new inserts only).
-- Recovery convention (2026-09-21): when a capture_unresolved card is later
-- resolved into a real post, the new context_captured event's payload
-- includes recovered_from_card_fingerprint matching the old event's
-- card_fingerprint. dashboardkien_group's recovery detection relies on this
-- link to stop counting a resolved card as invalid_unresolved_records.

create table if not exists scan_runs (
  id bigint generated always as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  mode text not null check (mode in ('feed','notifications','email','group_page','search','backfill','validation')),
  page_loads int not null default 0,
  posts_seen int not null default 0,
  new_listings int not null default 0,
  stopped_reason text,
  cursor text,
  group_id text references groups(id)
);
-- 75 rows. Was sublet_scan_runs; `group_key` -> `group_id`.

create table if not exists ops_state (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);
-- 12 rows. Notably `scrape_14_groups_batch` -- batch state for
-- sublet-scrape-14-groups/SKILL.md (JSON: batch_id, window_days, group_ids,
-- current_index, current_group, completed[], blocked[], status).

create table if not exists inbox (
  id bigint generated always as identity primary key,
  level text not null default 'info' check (level in ('info','action','warning','stop')),
  title text not null,
  body text,
  post_id uuid references posts(id),   -- was entity_type/entity_id, now specifically post_id
  created_at timestamptz not null default now(),
  read_at timestamptz,
  done_at timestamptz
);
-- 7 rows.

create table if not exists daily_metrics (
  id bigint generated always as identity primary key,
  day date not null default current_date,
  workflow text not null check (workflow in ('know','capture','analyze','demand','match','outreach','inbox','viewing','fee','ops')),
  metric text not null,
  value numeric,
  target numeric,
  meta jsonb,
  computed_at timestamptz not null default now(),
  unique (day, workflow, metric)
);
-- 25 rows. Was sublet_metrics.

create table if not exists jobs (
  id bigint generated always as identity primary key,
  job_type text not null check (job_type in ('scan','email','analyze','match','backfill','verify_group','followup','report','backup','groups_rank')),
  key text,
  priority int not null default 50,
  status text not null default 'queued' check (status in ('queued','running','done','failed','paused')),
  progress jsonb not null default '{}'::jsonb,
  attempts int not null default 0,
  next_run_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- 0 rows -- defined, unused.

-- Contacts the poster published themselves, split out by kind (2026-09-24,
-- Kien's explicit reversal of CLAUDE.md #5's old "no contact records" rule).
-- Filled only by refresh_post_contacts(): deterministic regex over posts.body
-- and outreach_availability_answers.answer1/answer2, plus the poster's
-- Facebook profile and the post link, for every post in
-- dashboardkien_outreach. Idempotent: re-running adds only what is missing.
-- Phones normalised to E.164 (Dutch 0x... -> +31x...); a phone is filed as
-- 'whatsapp' when the same text mentions WhatsApp. RLS on, no policies, and
-- revoked from anon/authenticated: the Roomie site must never read this.
create table if not exists post_contacts (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references posts(id) on delete cascade,
  poster_id uuid references posters(id) on delete set null,
  kind text not null check (kind in ('email','phone','whatsapp','telegram','instagram','facebook_profile','facebook_post')),
  value text not null,        -- normalised: lowercased email/handle, E.164 phone, URL
  raw text,                   -- as it appeared in the text (null for t.me handles)
  source text not null check (source in ('post_text','answer1','answer2','outreach_whatsapp_number','posters','posts')),
  extracted_at timestamptz not null default now(),
  unique (post_id, kind, value)
);
-- 2026-09-24 first run over 676 dashboard rows: email 97, whatsapp 20,
-- phone 27, telegram 30, instagram 6, facebook_profile 668, facebook_post 676.
-- Refresh: select * from refresh_post_contacts();
-- Read: public.outreach_contacts -- one row per dashboardkien_outreach row,
--   one column per kind (emails, whatsapp, phones, telegram, instagram,
--   facebook_profile), joined on posts.url = dashboardkien_outreach.post_link.

-- ---------- NOT migrated (existed in the old schema, do not exist live) ----------
-- sublet_seekers, sublet_matches, sublet_viewings, sublet_fees -- never had
-- real data, dropped rather than migrated. If a seeker/demand-side table is
-- built (e.g. for a WhatsApp intake form), name it without the `sublet_`
-- prefix to match the live convention (e.g. `seekers`), not `sublet_seekers`.

-- ---------- operator-facing views (the only two tables/views Kien reads) ----------
-- public.dashboardkien_group   -- scraping/recovery/data-readiness control
-- public.dashboardkien_outreach -- message1 outreach control
-- Full, current definitions: query pg_views, or see
-- docs/dashboard-source-of-truth.md (kept in sync with pg_views manually --
-- re-derive from pg_views if you suspect drift, don't trust this comment).

-- ---------- key indexes worth knowing about ----------
-- ux_outreach_messages_one_confirmed_message1_per_poster: unique on poster_id
--   where direction='out' and channel='fb_dm' and status='sent' and template
--   in the message1/legacy-availability-check set -- DB-level guarantee
--   against double-sending message1 to the same poster.
-- ux_outreach_messages_one_sent_per_poster_template: unique on
--   (poster_id, template) where channel='fb_dm' and direction='out' and
--   status='sent' -- same guarantee, generalized to message2/future stages.
-- ux_scan_runs_one_open_group_mode: unique on (group_id, mode) where
--   finished_at is null -- prevents two open scan runs for the same
--   group+mode at once.
-- jobs_open_uq: unique on (job_type, coalesce(key,'')) where status in
--   ('queued','running','paused').
